### ISSUE TITLE
Detect dead links in Markdown

### ISSUE THREAD

**Issue by kdeldycke** [kdeldycke/workflows#563]
Like in awesome lists:
- https://github.com/kdeldycke/awesome-billing/issues/75
- https://github.com/kdeldycke/awesome-iam/issues/112
- https://github.com/kdeldycke/awesome-engineering-team-management/issues/70

**Comment by ndsvw** [comment]
Maybe these are what you are looking for. These link-checks are not 100% reliable, but good enough IMO:
* https://github.com/tcort/markdown-link-check
* https://github.com/gaurav-nelson/github-action-markdown-link-check

**Comment by kdeldycke** [comment]
Thanks @ndsvw for the pointers. Found a better alternative in `lychee`:
- https://github.com/lycheeverse/lychee
- https://github.com/lycheeverse/lychee-action
